"""
Ollama AI Engine: Skill Evaluator

MCQ scoring stays deterministic (weighted by difficulty). Narrative feedback
is generated by the local Ollama model.
"""

from typing import Optional

from fastapi import HTTPException
from pydantic import BaseModel

from app.ai.ollama_client import chat_json


class AssessmentFeedback(BaseModel):
    feedback: str


def calculate_skill_score(questions: list, answers: dict, question_weights: dict = None) -> float:
    """
    Calculate normalized skill score (0-10) from MCQ answers.

    Uses weighted scoring based on question difficulty.
    Higher difficulty questions have more weight.
    """
    if not questions or not answers:
        return 0.0

    if question_weights is None:
        question_weights = {}

    total_weight = 0.0
    correct_weight = 0.0

    for q in questions:
        q_id = q['id']
        difficulty = q.get('difficulty', 3)
        weight = question_weights.get(q_id, difficulty)

        total_weight += weight

        if q_id in answers and answers[q_id] == q['correct_answer']:
            correct_weight += weight

    if total_weight == 0:
        return 0.0

    raw_score = correct_weight / total_weight
    normalized_score = raw_score * 10.0

    return round(normalized_score, 2)


def classify_skill_level(score: float) -> str:
    """Rule-based classification of skill level."""
    if score >= 7.5:
        return "Advanced"
    elif score >= 4.5:
        return "Intermediate"
    else:
        return "Beginner"


def _generate_feedback(skill_name: str, score: float, level: str, breakdown: dict) -> str:
    result = chat_json(
        system='Return JSON {"feedback":"two short sentences of coaching"}.',
        user=(
            f"{skill_name}: {score}/10 ({level}), "
            f"{breakdown.get('correct_answers')}/{breakdown.get('total_questions')} correct. "
            "What should they practice next?"
        ),
        schema=AssessmentFeedback,
        timeout=12.0,
        num_predict=80,
        retries=0,
    )
    return result.feedback


def generate_assessment_breakdown(
    questions: list,
    answers: dict,
    score: float,
    skill_name: Optional[str] = None,
) -> dict:
    """Generate detailed breakdown of assessment results, plus Ollama feedback."""
    total_questions = len(questions)
    correct_count = sum(1 for q in questions if answers.get(q['id']) == q['correct_answer'])

    difficulty_stats = {
        "1": {"total": 0, "correct": 0},
        "2": {"total": 0, "correct": 0},
        "3": {"total": 0, "correct": 0},
        "4": {"total": 0, "correct": 0},
        "5": {"total": 0, "correct": 0},
    }

    for q in questions:
        diff = str(q.get('difficulty', 3))
        difficulty_stats[diff]["total"] += 1
        if answers.get(q['id']) == q['correct_answer']:
            difficulty_stats[diff]["correct"] += 1

    accuracy_by_difficulty = {}
    for diff, stats in difficulty_stats.items():
        if stats["total"] > 0:
            accuracy_by_difficulty[f"difficulty_{diff}"] = {
                "accuracy": round((stats["correct"] / stats["total"]) * 100, 1),
                "correct": stats["correct"],
                "total": stats["total"]
            }

    level = classify_skill_level(score)
    breakdown = {
        "total_questions": total_questions,
        "correct_answers": correct_count,
        "overall_accuracy": round((correct_count / total_questions) * 100, 1) if total_questions > 0 else 0,
        "score": score,
        "level": level,
        "accuracy_by_difficulty": accuracy_by_difficulty,
    }

    try:
        breakdown["feedback"] = _generate_feedback(
            skill_name or "this skill",
            score,
            level,
            breakdown,
        )
    except HTTPException:
        breakdown["feedback"] = (
            f"You scored {score}/10 ({level}). Review missed questions and retry this skill."
        )

    return breakdown
